### ISSUE TITLE
ImBitArray in C

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#196]
@ocornut
Preparing cimgui for imgui 1.87 I have found ImBitArray with a static member (Size). I am completely unsure as to how this must be implemented in C

It is needed because `ImBitArray<ImGuiKey_NamedKey_COUNT> ActiveIdUsingKeyInputMask;` field

**Comment by ocornut** [comment]
I am unsure what is the best solution for you. You only need to figure out how to find the exact size for that structure (no need to expose it)...  I may have to use several more of those soon (also with `ImGuiKey_NamedKey_COUNT`), maybe you can hardcode support for `ImBitArray<>`.

Would it be possible to generate:
`char ActiveIdUsingKeyInputMask_Opaque[sizeof(ImBitArrayHeader) + sizeof(int) * ImGuiKey_NamedKey_COUNT) + 31) / 32]` would that compile?

**Comment by ocornut** [comment]
I'm actually working on a feature where I will be using this a lot so internally I am using a typedef:

```
typedef ImBitArray<ImGuiKey_NamedKey_COUNT, ImGuiKey_NamedKey_BEGIN>    ImBitArrayForNamedKeys;
```

You will be able to replace `ImBitArrayForNamedKey xxx` with `ImU32 xxx[(ImGuiKey_NamedKey_COUNT + 31) >> 5];` but preferable if you can manage more forms as well.

**Comment by ocornut** [comment]
FYI 1.87 should release this week (tomorrow?), I'll make a mention that it isn't yet supported in cimgui but should be later.

**Comment by sonoro1234** [comment]
I have managed to generate from master 1.87WIP
@epezent
The problem is that implot does not compile with it

**Comment by ocornut** [comment]
Great news!

> The problem is that implot does not compile with it

That's an internal change (since `IMGUI_VERSION_NUM > 18604`) for ImPlot to handle.
ImPlot is in this bit of an unusual situation where being widely adopted and using some internals it is bound to occasionally break while still trying to keep supporting a decent range of versions, so best to add a compile-time check and support both.

One day I'll survey usage of imgui_internals.h by ImPlot to see if there are things we can aim to standardize/make public.

Thanks!

**Comment by epezent** [comment]
@sonoro1234, using the latest versions of imgui maser and implot master, I am able to compile without issue. Actually, `BeginDragDropSourceEx` was removed recently but hasn't made a public release yet, so I'm guessing you are trying to compile with the v0.12 release instead of master? I can make a v0.13 release with the removal. 

@ocornut , that would be lovely! I'd by happy to help. One day I would also like to set up GitHub Actions for implot so that we can catch these types of things sooner.

**Comment by sonoro1234** [comment]
> I'm guessing you are trying to compile with the v0.12 release instead of master?

Yes

While trying to generate with last master I founded a duplicate declaration of `GetInputMap` in implot.h:1051 and implot_internal.h:1181

**Comment by epezent** [comment]
Fixed: b47c8ba

Thanks for the catch!

**Comment by sonoro1234** [comment]
Everything works fine. I will updated cimgui and cimplot when 1.87 is published.

**Comment by sonoro1234** [comment]
Everything is pushed but still based on imgui 1.86
