### ISSUE TITLE
`"ov_cimguiname :  igIsMouseDoubleClicked_Nil ,`, why this name changed?

### ISSUE THREAD

**Issue by gucio321** [cimgui/cimgui#262]
Hi there!
We have updated our dependencies in [cimgui-go](https://github.com/AllenDang/cimgui-go) last time.
I've noticed that some names have unexpectedly changed. e.g.:
```diff
-       ov_cimguiname :  igIsMouseDoubleClicked ,
+       ov_cimguiname :  igIsMouseDoubleClicked_Nil ,
```

Is this expected and should we handle this in our project or its a bug here?

**Comment by sonoro1234** [comment]
This is due to a new overloading in this function so that now there is `igIsMouseDoubleClicked_ID` and `igIsMouseDoubleClicked_Nil`

In LuaJIT-ImGui both functions get wrapped with those names and a generic version is created `IsMouseDoubleClicked` which calls one or the other deppending on argument types (emulation of overloading in LuaJIT)
