### ISSUE TITLE
Generate Binding feedback

### ISSUE THREAD

**Issue by sonoro1234** [cimgui/cimgui#71]
At least three people are generating bindings @mellinoe @Gekkio @ThisDrunkDane 
I am most interested in feedbacks/questions about how this is working

**Comment by ThisDrunkDane** [comment]
So far it seems alright, I'm still using https://github.com/sonoro1234/cimgui/ as the submodule and targeting v1.64 (since v1.65 is just more refactoring). My main hopes is just that cimgui will update faster so I'm the sole bottleneck of updates, instead of having to wait for cimgui to update.
Also, down in https://github.com/cimgui/cimgui#example-bindings-based-on-cimgui is says odin-dear_imgui but it's now just odin-imgui

**Comment by sonoro1234** [comment]
Hi Mikkel

Thanks for feedback!!
sonoro1234/cimgui will be always even with cimgui/cimgui

Will update you link in readme

I am most interested in how you can automate the generation of your bindings with the help of lua/json files

**Comment by ThisDrunkDane** [comment]
While it probably can be done, I'm not any lua expert, nor do I really want to be so somebody else would probably have to pick up the torch, Odin is also quite different than C++ so it would probably be quite a bit more involved than the C generation (Odin can't bind to C++ so it would still have to bind to the C-binding LIB).

The enum generation for example is pretty straight forward tho' so a partial generation would most likely be possible (and it's mainly structs and enums changing that drive some headaches when updating)

**Comment by sonoro1234** [comment]
You are not expected to use Lua at all:
The json files were generated so that you could work with them from your choice language (odin?) to generate odin code.

**Comment by ThisDrunkDane** [comment]
Oh I see, now that will be most likely be _very_ useful, I'll check it out and try to do some auto-gen when I get time and get back to you!

**Comment by Gekkio** [comment]
Seems pretty good so far! I just updated `imgui-rs` to use latest cimgui. In `imgui-rs`, the biggest value of cimgui is the generated C-binding lib itself, because Rust can't directly bind to C++ (*). Having the C binding generated automatically makes upgrades much easier, and before this change `imgui-rs` was stuck with an old version of Dear Imgui for quite some time.

Right now I've manually generated the corresponding Rust definitions from `cimgui.h`, but I'm thinking about switching to Rust bindgen, which can generate bindings to any C library. The json/lua stuff isn't important for me, because bindgen can already take care of generating the corresponding Rust code if a C header file is available.

In the latest update, I went through all the stuff in `cimgui.h`, and found one thing that felt inconsistent to me. The ID push functions for string and range look like this:

```
CIMGUI_API void igPushIDStr(const char* str_id);
CIMGUI_API void igPushIDRange(const char* str_id_begin,const char* str_id_end);
```

But the range overload is named differently in the getter version:

```
CIMGUI_API ImGuiID igGetIDStr(const char* str_id);
CIMGUI_API ImGuiID igGetIDStrStr(const char* str_id_begin,const char* str_id_end);
```

(*) Rust bindgen can actually generate bindings to C++, but the generated bindings are not portable at all so in practice it adds bindgen and LLVM as a build-time dependency. I'd much rather run bindgen manually just once after every time I upgrade `cimgui`.

**Comment by sonoro1234** [comment]
Hi Joonas,
Thanks for reporting

igPushIDRange got his name from a manual written overloading table with the purpose of keeping some names used in cimgui 1.53. I did that with very few functions as this is what seem desirable in an automatic generation. I agree that if we have igPushIDRange then we should also have igGetIDRange. I will push that in a while.

As for the json usefullness, in the case of LuaJIT it suffices with the C header given as a string to the function ffi.cdef for getting a C binding and thats all. But with the help of definitions.lua I could wrap this ffi.cdef functions with anothers taking care of defaults for arguments and also for embedding some functions in the structs they belong to in an automated way. I dont know if bindgen does the same.

Regards
victor bombi

**Comment by ThisDrunkDane** [comment]
One thing I noticed in the json that would be a minor convenience improvement is under the structs. `{"type":"ImVector/*<ImVec4>*/","name":"_ClipRectStack"}` Whenever the type is a ImVector, it would be cool to instead of having the "type" embedded in a comment, it could be an additional field, in Odin we have para-poly so we can actually specialize it. it isn't a big problem to just get it out of the comment, it's just a minor convenience thing I noticed.

**Comment by sonoro1234** [comment]
That was a design decision that could change in the future.
As there are only two function using ImVector:
>void TextRange_split(TextRange* self,char separator,ImVector_TextRange* out);
>void GlyphRangesBuilder_BuildRanges(GlyphRangesBuilder* self,ImVector_ImWchar* out_ranges);
And I am not using them I decided to wrap all ImVector templates as
>struct ImVector
{
    int Size;
    int Capacity;
    void* Data;
};

which simplifies things alot. You can then cast Data to any type if you need to use it. So I just included the template type in a comment.
If we begin to use ImVector variants from bindings, I should create several different types as ImVector_ImVec4, ImVector_TexRange, etc
This step will be taken when there is a clear use case for that

**Comment by ThisDrunkDane** [comment]
My ImVector looks like this ```
ImVector :: struct(T : type) {
    size     : i32,
    capacity : i32,
    data     : ^T,
}
``` so having ImVector_ImVec4 etc etc would be a pretty big downgrade for me as I just do `ImVector(f64)` and stuff like that in Odin code. and ImVector is used in several structs which is why having the extra json field would just ease with generation

**Comment by ThisDrunkDane** [comment]
The C output could still just put them in a comment, but having the type in a seperate field in the json would just help with generation for other languages

**Comment by sonoro1234** [comment]
@ThisDrunkDane Just pushed

**Comment by Gekkio** [comment]
Noticed one minor thing: `stdint.h` should be included in the beginning of `cimgui.h` when compiling with a C compiler, because the file uses `int64_t` and `uint64_t`. The file probably gets included anyway with many compilers (through `stdio.h` maybe...?), but some compilers/tools are stricter and compilation may fail.

BTW, I started playing with bindgen a bit, and the JSON files are actually very useful for whitelisting stuff and configuring the binding generation :smile:

**Comment by sonoro1234** [comment]
cimgui.cpp and cimgui.h are never expected to be compiled by a C compiler, but with a C++ compiler because it goes with all imgui.cpp stuff. But cimgui.h indeed is expected to be used in C compiler by defining
CIMGUI_DEFINE_ENUMS_AND_STRUCTS so I have just added this include

**Comment by dpethes** [comment]
I'm switching the pascal binding to auto-generation from JSON files as well. Only two small issues I encountered so far: 
* the function ordering in definitions.json seems to be somewhat random, it would be a bit clearer if it preserved the original order from imgui.h
* no Visual studio project file to build and debug from, but maybe I can throw something together

**Comment by sonoro1234** [comment]
Visual studio project file can be generated easily from CMake.

When the keys are not numbers (table as a key-value set) there is not ordering in Lua unless you do something, may be I could sort the key values alphabetically

**Comment by dpethes** [comment]
It should be enough to insert the line number as another key/value to the entries. Each generator could sort the entries by line number then, if desired.
  The indentation makes it easier to read when something goes wrong, thanks!

**Comment by mellinoe** [comment]
Hey @sonoro1234, I was experimenting this week with generating bindings for the viewport branch. Almost everything works as-is, but there is one tricky issue to be dealt with, again relating to the "non-UDT" return type problem. Consider these two fields on `ImGuiPlatformIO`:

```C++
ImVec2 (*Platform_GetWindowPos)(ImGuiViewport* vp);
ImVec2 (*Platform_GetWindowSize)(ImGuiViewport* vp);
```

My application crashes when one of these function pointers is invoked if they are declared as above, but work if I change the return type to an `ImVec2*` out parameter (like the "nonUDT" overloads you added). This different from before, though, because these are function pointers that need to be passed into imgui, rather than function exports that can be "redirected" through other entry points.

Any thoughts on how to approach this? I fear that it might be difficult to solve without changes to imgui itself.

**Comment by sonoro1234** [comment]
Or we do a manual to use instead of this struct member (horrible solution in which would be possible to accidentaly call the struct member getting a crash) or @ocornut changes it to return a `ImVec2 *`

**Comment by ocornut** [comment]
I technically could make all those function pointers pass return value as pointer arguments, the problem is that it would make it inconsistent with the rest of the general C++ API.

(It would also break build for everyone compiling viewport-enabled bindings but I don’t mind this as much)

I’m not sure I understand the problem enough to think about solution. Those functions would strictly be called from the C++ code. Is your problem that you cannot fill in this field with a function pointer leading to your language? If so could they somehow be wrapped in cimgui?

**Comment by sonoro1234** [comment]
The general strategy in cimgui is to verbatim copy all structs in imgui (except for member functions that are auto-wrapped in exported C functions) 
This are not member functions but pointer to functions which is a valid C field in a struct and can be used directly by C, except that this two function return a UDT (user defined type or non POD value) and this is not a good C type.
To make this fields to point  C valid functions, they should be manually generated (as they are not member functions)

```cpp

ImVec2* ImGuiPlatformIO_Platform_GetWindowPos(ImGuiPlatformIO pio, ImGuiViewport* vp)
{
    return &pio.Platform_GetWindowPos(vp);
}
```
And the "manually generated" solution dont stops here:
ImGuiPlatformIO_C struct could not be a verbatim copy of ImGuiPlatformIO because the function signature changes, so that `GetPlatformIO()` would not return the expected ImGuiPlatformIO_C_version but the C++ one in which two fields in ImGuiPlatformIO that could not be used at all.

**Comment by mellinoe** [comment]
> Is your problem that you cannot fill in this field with a function pointer leading to your language?

Effectively, yes, this seems to be the problem. Other languages are only able to fill in C-compatible function pointers, and because of the return types of the two functions above, they are not C-compatible.

> If so could they somehow be wrapped in cimgui?

Possibly -- I think some experimentation would have to be done. I can imagine that we could provide something like:

```C++
extern "C" void Register_Platform_GetWindowPos(
    ImGuiPlatformIO* platform_io,
    void(*user_callback)(ImGuiViewport* vp, ImVec2* out_pos))
{
    // store user_callback somewhere, and hook it up to platform_io->Platform_GetWindowPos through a lambda?
}

extern "C" void Register_Platform_GetWindowSize(...){ } // Same for this function
```

The question then becomes where you store `user_callback` so that it can be invoked through the function pointer attached to `platform_io->Platform_GetWindowPos`. As far as I know there's no extra data being injected into regular ImGui structs (which `ImGuiPlatformIO` is) anywhere else.

**Comment by mellinoe** [comment]
@sonoro1234 The problem is that the C++ side attempts to invoke these function pointers, it sounds like you are describing a way that the function pointers could be invoked safely from the outside, which isn't the interesting portion (since they are provided from the outside to begin with).

**Comment by ocornut** [comment]
> The question then becomes where you store user_callback

I assumed cimgui had its own storage, it could hold an array updated with igCreateContext/igDestroyContext?

```
struct cimgui_data
{
  ImGuiContext* Context;
  // ... more data
}
```

As also desirable for rendering/platform binding I could add a `void*` for the language binding in ImGuiIO?

```
void* BackendPlatformUserData;
void* BackendRendererUserData;
void* BackendLanguageUserData;
```
?

**Comment by sonoro1234** [comment]
There is no separated storage. All structs returned are really imgui structs.

```cpp
CIMGUI_API ImGuiContext* igCreateContext(ImFontAtlas* shared_font_atlas)
{
    return ImGui::CreateContext(shared_font_atlas);
}
```

**Comment by ocornut** [comment]
I'll add the extra void* to make it easier if you want to create your own storage and link it to the context.

**Comment by ocornut** [comment]
Done here https://github.com/ocornut/imgui/commit/5691385a33dc359acb2fa74267d96a6bac85c924

**Comment by sonoro1234** [comment]
I think this path is over-complication.
Platform_GetWindowPos field is already setted in the implementations (which can be used from C without changes as done in LuaJIT-imgui) and then just avoid using them directly but instead use

```cpp

ImVec2* ImGuiPlatformIO_Platform_GetWindowPos(ImGuiPlatformIO *pio, ImGuiViewport* vp)
{
    return &(pio->Platform_GetWindowPos(vp));
}
```
will need to be manually generated (which I dont like) But the BackendRendererUserData would need that also (but worse)

**Comment by ocornut** [comment]
It is invalid to return the address of a local variable., Needs to be:
```
void ImGuiPlatformIO_Platform_GetWindowPos(ImGuiPlatformIO *pio, ImGuiViewport* vp, ImVec2* out_pos)
{
    *out_pos = pio->Platform_GetWindowPos(vp);
}
```

As I understand @mellinoe maybe this wouldn't solve his problem however?

**Comment by sonoro1234** [comment]
better
```cpp

ImVec2_simple ImGuiPlatformIO_Platform_GetWindowPos(ImGuiPlatformIO *pio, ImGuiViewport* vp)
{
    ImVec2 ret = pio->Platform_GetWindowPos(vp);
    ImVec2_Simple ret2 = ImVec2ToSimple(ret);
   return ret2;
}
```

**Comment by mellinoe** [comment]
I think that solution is still misunderstanding the main problem, which is that I can't actually set `pio->Platform_GetWindowPos` to a valid function pointer. So even with that code, the first line would crash the application.

**Comment by sonoro1234** [comment]
This `pio->Platform_GetWindowPos` would be used in cimgui.cpp (which is cpp so it can be used)
 You would then use `ImGuiPlatformIO_Platform_GetWindowPos` from C without any problem

**Comment by mellinoe** [comment]
To clarify, I don’t actually want to call these function pointers. They are invoked exclusively by the native ImGui implementation to refresh its understanding of where all of the app’s windows are at/their sizes. User code just sets them up and hands them over during initialization. In my app, they end up pointing to some C# method which I could just call directly if I wanted to. Most of the function pointers on ImGuiPlatformIO work fine and the C++ side can invoke them without a problem, save for the two in question above.

**Comment by sonoro1234** [comment]
` In my app, they end up pointing to some C# method which I could just call directly if I wanted to`
This seems the problem. They cant be set to a C# method
https://github.com/ocornut/imgui/blob/viewport/imgui.h#L2180
is setted in
https://github.com/ocornut/imgui/blob/viewport/examples/imgui_impl_glfw.cpp#L692

**Comment by mellinoe** [comment]
There is still some confusion. I can assign most of these function pointers just fine — C# has support for creating C-compatible function pointers for regular C# methods, which I can pass over to the C++ side. In order to set up the “platform handling” for the new viewport feature, you have to fill in that structure with a bunch of pointers for various things to keep the state up to date. That is what the GLFW example code is doing, and is what I am now doing in my C# setup code.

**Comment by ocornut** [comment]
I don't understand what's going on, you guys should probably have a topic for this.
When it is sorted please let me know if you are using the storage field `void* BackendLanguageUserData` otherwise I will remove it from the structure.

**Comment by sonoro1234** [comment]
Sorry for not understanding. I will try again.
You are trying to do from C# what is done in
https://github.com/ocornut/imgui/blob/viewport/examples/imgui_impl_glfw.cpp#L692
But as this is not C but Cpp (Because of returning UDT) you cant.

You should elaborate the proposed Register_Platform_GetWindowPos solution which I am not completely understanding. But in the end you will have to set somehow this function pointer field.

**Comment by mellinoe** [comment]
> But as this is not C but Cpp (Because of returning UDT) you cant.

Yes, that’s correct. Sorry for the back and forth. I will try to elaborate on the alternative tonight, and verify that it actually works.

**Comment by mellinoe** [comment]
I [pushed a branch](https://github.com/mellinoe/cimgui/commit/b96773efee82abe1f86aa1ccf2309f43da3ec824) to my fork that changes the imgui submodule to point to the latest viewport branch, and adds the workaround described above. It's a proof-of-concept and we'd probably want to do it slightly differently and automatically as part of the generator (if that is feasible). But the general approach works. See [cimgui_extra.cpp](https://github.com/mellinoe/cimgui/blob/b96773efee82abe1f86aa1ccf2309f43da3ec824/cimgui_extra.cpp) for the main addition.

**Comment by sonoro1234** [comment]
If I am not confused ImGui is not using C++11, so I would prefer not using it.
Excuse my bad C++ knowledge but it seems that platform_io is not used so should be dropped.
This is the not C++11 proposal. Does it work the same?

```cpp
ImVec2 Platform_GetWindowPos_hook(ImGuiViewport* vp)
    {
        ImVec2 pos;
        GetCimguiStorage().Platform_GetWindowPos(vp, &pos);
        return pos;
    };

CIMGUI_API void ImGuiPlatformIO_Set_Platform_GetWindowPos( void(*user_callback)(ImGuiViewport* vp, ImVec2* out_pos))
{
    CimguiStorage storage = GetCimguiStorage();
    storage.Platform_GetWindowPos = user_callback;
    platform_io->Platform_GetWindowPos = Platform_GetWindowPos_hook;
}
```
As for the generator.lua change I would like to test the problem that lead to that.

**Comment by mellinoe** [comment]
@sonoro1234 Sorry that I didn't respond to that last message. Your version of it looks like it will work just as well, and is simpler. 👍
